#!/bin/sh

if [ "$1" = "clean" ] ; then
   echo "Cleaning..."
   rm -rf cordova-app
fi

cordova create cordova-app org.mojojs.kitchensink MojoKitchensink --link-to=src/web
cd cordova-app
cordova platforms add android
# cordova platforms add ios

cordova plugin add https://github.com/apache/cordova-plugin-network-information.git
# cordova plugin add https://github.com/wildabeast/BarcodeScanner.git
